{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deploy.name }}-config
  namespace: {{ .Values.namespace }}
data:
  .env: |
    {{- .Values.configValues | nindent 4 -}}
{{- end }}